version: '3.8.0'

services:
  app:
    build: .
    env_file:
      - .env
    container_name: medods-auth-service
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: